name: Spotless Formatting

on:
  push:
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: write
  pull-requests: write

jobs:
  spotless:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run Spotless Check
        id: check
        continue-on-error: true
        run: |
          OUTPUT=$(./gradlew spotlessCheck --parallel --no-daemon 2>&1)
          echo "::set-output name=output::$OUTPUT"

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.check.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const output = process.env.SPOTLESS_OUTPUT;

            const comment = `### ❌ Spotless Formatting — Check Failed

            Your pull request includes code that does not comply with the project's formatting standards. To resolve this issue, please follow the steps below:

            1. Execute the following command in your local repository to automatically apply the correct formatting:  
               \`\`\`bash  
               ./gradlew spotlessApply  
               \`\`\`

            2. After running the command, review the updated files to ensure all changes are expected.

            3. Stage the updated files, commit them with an appropriate message, and push the changes to your branch.

            ---

            _This is an automated message generated by the [Spotless code formatting check system](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/blob/main/.github/workflows/spotless.yml)._

            <details>
            <summary>Detailed Output</summary>

            \`\`\`
            ${output}
            \`\`\`
            </details>`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          SPOTLESS_OUTPUT: ${{ steps.check.outputs.output }}

      - name: Run Spotless Apply
        if: steps.check.outcome == 'failure'
        run: ./gradlew spotlessApply --parallel --no-daemon

      - name: Commit and push changes
        if: steps.check.outcome == 'failure' && github.event_name != 'pull_request'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: apply spotless formatting [skip ci]" && git push)
